### ISSUE TITLE
Where to contribute to Mini SE support?

### ISSUE THREAD

**Issue by kripper** [m4xw/rosettadrone_mini2#18]
I'm interested in writing AI scripts for the Mini SE.
This fork looks more up to date for the Mini 2.
Should I contribute to this fork or to the original repo?
Will you release a pull request?

**Comment by m4xw** [comment]
Hi,
historically this fork is more tuned for Mini 2 but it should be ideal for any DJI drone that works with virtual joystick instead of DJI waypoints.
If you need DJI waypoints, use upstream. If you want fine tuned virtstick with optimized PID tuning for each drone metric or u need failsafe video stream & passthrough to QGC then use mine. The vid transmission is more noise heavy and higher latency but it works even when dji fly fails to transfer video feed at the edge of transfer range or with phones that dont work properly with DJI's video decoder (i plan to bring low latency back as a option tho).
Also be aware this fork is using the GPL license (but I gave upstream a license agreement for everything the1only wants to backport)
Some things like surveys from QGC only work with pre-computed waypoints as the automatic intermediate waypoint generation is stubbed (need to find a good solution there).

Here is a link to the upstream PR (which wont get merged anytime soon): https://github.com/The1only/rosettadrone/pull/76

**Comment by kripper** [comment]
Hi @m4xw,

So the upstream repo does still not support virtual-stick-controled-waypoints?
I expected rossettadrone to convert the waypoints into virtual stick commands in order tu support the mini series.
Why did you have to inject your code into DJI's SDK?
Is it still necessary now that the SDK supports the mini?

**Comment by m4xw** [comment]
> So the upstream repo does still not support virtual-stick-controled-waypoints?

correct afaik

> I expected rossettadrone to convert the waypoints into virtual stick commands in order tu support the mini series.

> Why did you have to inject your code into DJI's SDK?
> Is it still necessary now that the SDK supports the mini?

Because DJI did not support Mini 2 and didn't plan to add support back then so I said fuck it and made it work.
Its no longer required (unless u want to use mini 3 but there virtstick seems to get rejected by the FC...)
